// Shared defaults for recording, review, and document generation.
globalThis.ChronoDefaults = {
  configVersion: 9,
  recording: { ...ChronoPolicy.defaults },
  projectRoot: "${HOME}/sistemas/cronoPrint",
  documentTitle: "Procedimento gravado",
  sectionTitlePattern: "{sectionNumber}. {pageName}",
  screenshotCaptionPattern: "Figura {sectionNumber}.{screenNumber} — {pageName}",
  tableCaptionPattern: "Tabela {sectionNumber}.{tableNumber} — Passos de {pageName}",
  showScreenshotCaption: true,
  showTableCaption: true,
  showCaptureErrorsInDocx: true,
  showTableOfContents: false,
  stepPresentation: "table",
  actionLayoutRules: "",
  groupWindowMs: 0,
  columns: [
    { key: "step", title: "STEP", source: ["sequence"], width: 12, alignment: "center" },
    {
      key: "description",
      title: "DESCRIÇÃO",
      source: ["auto-description", "microprint"],
      width: 88,
      alignment: "left",
    },
  ],
  actionTexts: {
    "click-menu": "Acione o menu {value}.",
    "click-styled-button": "Acione o botão {value}.",
    "click-button": "Clique no botão {name}.",
    "click-link": "Clique no link {name}.",
    "click-field": "Selecione o campo {name}.",
    click: "Clique em {name}.",
    "double-click": "Dê um duplo clique em {name}.",
    "right-click": "Acione o botão direito do mouse em {name}.",
    typing: "Insira o texto {value} no campo {name}.",
    select: "Selecione uma opção no campo {name}.",
    toggle: "Altere a opção {name}.",
    change: "Altere o campo {name}.",
    observation: "Observe {name}.",
    "highlight-text": "Certifique-se que {texto-iluminado}.",
    "page-view": "Insira a url {url} e acesse a página {pageName}",
    scroll: "Role a página até a posição {scrollY}.",
    "scroll-combined": "Role a página e {action}",
    generic: "Interaja com {name}.",
  },
  microprint: { heightPt: 11, maxWidthPt: 90, preserveAspectRatio: true },
  markers: { sizePt: 18 },
  images: {
    screen: { format: "jpeg", quality: 82, maxWidth: 1920, maxHeight: 1080 },
    component: {
      format: "png",
      quality: 92,
      maxWidth: 600,
      maxHeight: 300,
      padding: 18,
      upscale: false,
    },
  },
  theme: {
    fontFamily: "Aptos",
    bodyFontSize: 11,
    headingColor: "111827",
    tableHeaderBackground: "285589",
    tableHeaderColor: "FFFFFF",
    tableBorderColor: "111111",
    markerBackground: "000000",
    markerColor: "FFFFFF",
    componentBold: true,
    componentColor: "111827",
    linkColor: "0563C1",
    titleBefore: 0,
    titleAfter: 18,
    screenBefore: 6,
    screenAfter: 12,
    tableBefore: 8,
    tableAfter: 18,
  },
};
